version: '3'

services:
    database:
        image: 'bitnami/postgresql'
        ports:
            - '5432:5432'
        environment:
            - POSTGRESQL_USERNAME=docker
            - POSTGRESQL_PASSWORD=docker
            - POSTGRESQL_DATABASE=app
        volumes:
            - 'postgresql_data:/bitnami/postgresql'
        networks:
            - app-net
    redis:
      image: 'bitnami/redis'
      ports:
        - '6379:6379'
      environment:
        - ALLOW_EMPTY_PASSWORD=yes
      volumes:
        - 'redis_data:/bitnami/redis/data'
      networks:
        - app-net

networks:
    app-net:
        driver: bridge

volumes:
    postgresql_data:
        driver: local
    redis_data:
        driver: local
